/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.pojo.test.testdata.included.package1;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EnumStruct implements org.apache.thrift.TEnum {
  VAL1(1),
  VAL2(2);

  private final int value;

  private EnumStruct(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EnumStruct findByValue(int value) { 
    switch (value) {
      case 1:
        return VAL1;
      case 2:
        return VAL2;
      default:
        return null;
    }
  }
}
