/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.disges.thrift.plugin.testdata.objects.included.package1;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TestListStruct implements org.apache.thrift.TBase<TestListStruct, TestListStruct._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TestListStruct");

  private static final org.apache.thrift.protocol.TField SIMPLE_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("simpleList", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField REF_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("refList", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField REF_OTHER_PACKAGE_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("refOtherPackageList", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TestListStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TestListStructTupleSchemeFactory());
  }

  public List<Integer> simpleList; // required
  public List<SimpleStruct> refList; // required
  public List<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2> refOtherPackageList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SIMPLE_LIST((short)1, "simpleList"),
    REF_LIST((short)2, "refList"),
    REF_OTHER_PACKAGE_LIST((short)3, "refOtherPackageList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SIMPLE_LIST
          return SIMPLE_LIST;
        case 2: // REF_LIST
          return REF_LIST;
        case 3: // REF_OTHER_PACKAGE_LIST
          return REF_OTHER_PACKAGE_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SIMPLE_LIST, new org.apache.thrift.meta_data.FieldMetaData("simpleList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.REF_LIST, new org.apache.thrift.meta_data.FieldMetaData("refList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SimpleStruct.class))));
    tmpMap.put(_Fields.REF_OTHER_PACKAGE_LIST, new org.apache.thrift.meta_data.FieldMetaData("refOtherPackageList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TestListStruct.class, metaDataMap);
  }

  public TestListStruct() {
  }

  public TestListStruct(
    List<Integer> simpleList,
    List<SimpleStruct> refList,
    List<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2> refOtherPackageList)
  {
    this();
    this.simpleList = simpleList;
    this.refList = refList;
    this.refOtherPackageList = refOtherPackageList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TestListStruct(TestListStruct other) {
    if (other.isSetSimpleList()) {
      List<Integer> __this__simpleList = new ArrayList<Integer>();
      for (Integer other_element : other.simpleList) {
        __this__simpleList.add(other_element);
      }
      this.simpleList = __this__simpleList;
    }
    if (other.isSetRefList()) {
      List<SimpleStruct> __this__refList = new ArrayList<SimpleStruct>();
      for (SimpleStruct other_element : other.refList) {
        __this__refList.add(new SimpleStruct(other_element));
      }
      this.refList = __this__refList;
    }
    if (other.isSetRefOtherPackageList()) {
      List<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2> __this__refOtherPackageList = new ArrayList<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2>();
      for (org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2 other_element : other.refOtherPackageList) {
        __this__refOtherPackageList.add(new org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2(other_element));
      }
      this.refOtherPackageList = __this__refOtherPackageList;
    }
  }

  public TestListStruct deepCopy() {
    return new TestListStruct(this);
  }

  @Override
  public void clear() {
    this.simpleList = null;
    this.refList = null;
    this.refOtherPackageList = null;
  }

  public int getSimpleListSize() {
    return (this.simpleList == null) ? 0 : this.simpleList.size();
  }

  public java.util.Iterator<Integer> getSimpleListIterator() {
    return (this.simpleList == null) ? null : this.simpleList.iterator();
  }

  public void addToSimpleList(int elem) {
    if (this.simpleList == null) {
      this.simpleList = new ArrayList<Integer>();
    }
    this.simpleList.add(elem);
  }

  public List<Integer> getSimpleList() {
    return this.simpleList;
  }

  public TestListStruct setSimpleList(List<Integer> simpleList) {
    this.simpleList = simpleList;
    return this;
  }

  public void unsetSimpleList() {
    this.simpleList = null;
  }

  /** Returns true if field simpleList is set (has been assigned a value) and false otherwise */
  public boolean isSetSimpleList() {
    return this.simpleList != null;
  }

  public void setSimpleListIsSet(boolean value) {
    if (!value) {
      this.simpleList = null;
    }
  }

  public int getRefListSize() {
    return (this.refList == null) ? 0 : this.refList.size();
  }

  public java.util.Iterator<SimpleStruct> getRefListIterator() {
    return (this.refList == null) ? null : this.refList.iterator();
  }

  public void addToRefList(SimpleStruct elem) {
    if (this.refList == null) {
      this.refList = new ArrayList<SimpleStruct>();
    }
    this.refList.add(elem);
  }

  public List<SimpleStruct> getRefList() {
    return this.refList;
  }

  public TestListStruct setRefList(List<SimpleStruct> refList) {
    this.refList = refList;
    return this;
  }

  public void unsetRefList() {
    this.refList = null;
  }

  /** Returns true if field refList is set (has been assigned a value) and false otherwise */
  public boolean isSetRefList() {
    return this.refList != null;
  }

  public void setRefListIsSet(boolean value) {
    if (!value) {
      this.refList = null;
    }
  }

  public int getRefOtherPackageListSize() {
    return (this.refOtherPackageList == null) ? 0 : this.refOtherPackageList.size();
  }

  public java.util.Iterator<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2> getRefOtherPackageListIterator() {
    return (this.refOtherPackageList == null) ? null : this.refOtherPackageList.iterator();
  }

  public void addToRefOtherPackageList(org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2 elem) {
    if (this.refOtherPackageList == null) {
      this.refOtherPackageList = new ArrayList<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2>();
    }
    this.refOtherPackageList.add(elem);
  }

  public List<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2> getRefOtherPackageList() {
    return this.refOtherPackageList;
  }

  public TestListStruct setRefOtherPackageList(List<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2> refOtherPackageList) {
    this.refOtherPackageList = refOtherPackageList;
    return this;
  }

  public void unsetRefOtherPackageList() {
    this.refOtherPackageList = null;
  }

  /** Returns true if field refOtherPackageList is set (has been assigned a value) and false otherwise */
  public boolean isSetRefOtherPackageList() {
    return this.refOtherPackageList != null;
  }

  public void setRefOtherPackageListIsSet(boolean value) {
    if (!value) {
      this.refOtherPackageList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SIMPLE_LIST:
      if (value == null) {
        unsetSimpleList();
      } else {
        setSimpleList((List<Integer>)value);
      }
      break;

    case REF_LIST:
      if (value == null) {
        unsetRefList();
      } else {
        setRefList((List<SimpleStruct>)value);
      }
      break;

    case REF_OTHER_PACKAGE_LIST:
      if (value == null) {
        unsetRefOtherPackageList();
      } else {
        setRefOtherPackageList((List<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SIMPLE_LIST:
      return getSimpleList();

    case REF_LIST:
      return getRefList();

    case REF_OTHER_PACKAGE_LIST:
      return getRefOtherPackageList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SIMPLE_LIST:
      return isSetSimpleList();
    case REF_LIST:
      return isSetRefList();
    case REF_OTHER_PACKAGE_LIST:
      return isSetRefOtherPackageList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TestListStruct)
      return this.equals((TestListStruct)that);
    return false;
  }

  public boolean equals(TestListStruct that) {
    if (that == null)
      return false;

    boolean this_present_simpleList = true && this.isSetSimpleList();
    boolean that_present_simpleList = true && that.isSetSimpleList();
    if (this_present_simpleList || that_present_simpleList) {
      if (!(this_present_simpleList && that_present_simpleList))
        return false;
      if (!this.simpleList.equals(that.simpleList))
        return false;
    }

    boolean this_present_refList = true && this.isSetRefList();
    boolean that_present_refList = true && that.isSetRefList();
    if (this_present_refList || that_present_refList) {
      if (!(this_present_refList && that_present_refList))
        return false;
      if (!this.refList.equals(that.refList))
        return false;
    }

    boolean this_present_refOtherPackageList = true && this.isSetRefOtherPackageList();
    boolean that_present_refOtherPackageList = true && that.isSetRefOtherPackageList();
    if (this_present_refOtherPackageList || that_present_refOtherPackageList) {
      if (!(this_present_refOtherPackageList && that_present_refOtherPackageList))
        return false;
      if (!this.refOtherPackageList.equals(that.refOtherPackageList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TestListStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TestListStruct typedOther = (TestListStruct)other;

    lastComparison = Boolean.valueOf(isSetSimpleList()).compareTo(typedOther.isSetSimpleList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSimpleList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.simpleList, typedOther.simpleList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRefList()).compareTo(typedOther.isSetRefList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRefList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.refList, typedOther.refList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRefOtherPackageList()).compareTo(typedOther.isSetRefOtherPackageList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRefOtherPackageList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.refOtherPackageList, typedOther.refOtherPackageList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TestListStruct(");
    boolean first = true;

    sb.append("simpleList:");
    if (this.simpleList == null) {
      sb.append("null");
    } else {
      sb.append(this.simpleList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("refList:");
    if (this.refList == null) {
      sb.append("null");
    } else {
      sb.append(this.refList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("refOtherPackageList:");
    if (this.refOtherPackageList == null) {
      sb.append("null");
    } else {
      sb.append(this.refOtherPackageList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (simpleList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'simpleList' was not present! Struct: " + toString());
    }
    if (refList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'refList' was not present! Struct: " + toString());
    }
    if (refOtherPackageList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'refOtherPackageList' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TestListStructStandardSchemeFactory implements SchemeFactory {
    public TestListStructStandardScheme getScheme() {
      return new TestListStructStandardScheme();
    }
  }

  private static class TestListStructStandardScheme extends StandardScheme<TestListStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TestListStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SIMPLE_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list50 = iprot.readListBegin();
                struct.simpleList = new ArrayList<Integer>(_list50.size);
                for (int _i51 = 0; _i51 < _list50.size; ++_i51)
                {
                  int _elem52; // required
                  _elem52 = iprot.readI32();
                  struct.simpleList.add(_elem52);
                }
                iprot.readListEnd();
              }
              struct.setSimpleListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REF_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list53 = iprot.readListBegin();
                struct.refList = new ArrayList<SimpleStruct>(_list53.size);
                for (int _i54 = 0; _i54 < _list53.size; ++_i54)
                {
                  SimpleStruct _elem55; // required
                  _elem55 = new SimpleStruct();
                  _elem55.read(iprot);
                  struct.refList.add(_elem55);
                }
                iprot.readListEnd();
              }
              struct.setRefListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REF_OTHER_PACKAGE_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list56 = iprot.readListBegin();
                struct.refOtherPackageList = new ArrayList<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2>(_list56.size);
                for (int _i57 = 0; _i57 < _list56.size; ++_i57)
                {
                  org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2 _elem58; // required
                  _elem58 = new org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2();
                  _elem58.read(iprot);
                  struct.refOtherPackageList.add(_elem58);
                }
                iprot.readListEnd();
              }
              struct.setRefOtherPackageListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TestListStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.simpleList != null) {
        oprot.writeFieldBegin(SIMPLE_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.simpleList.size()));
          for (int _iter59 : struct.simpleList)
          {
            oprot.writeI32(_iter59);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.refList != null) {
        oprot.writeFieldBegin(REF_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.refList.size()));
          for (SimpleStruct _iter60 : struct.refList)
          {
            _iter60.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.refOtherPackageList != null) {
        oprot.writeFieldBegin(REF_OTHER_PACKAGE_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.refOtherPackageList.size()));
          for (org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2 _iter61 : struct.refOtherPackageList)
          {
            _iter61.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TestListStructTupleSchemeFactory implements SchemeFactory {
    public TestListStructTupleScheme getScheme() {
      return new TestListStructTupleScheme();
    }
  }

  private static class TestListStructTupleScheme extends TupleScheme<TestListStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TestListStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.simpleList.size());
        for (int _iter62 : struct.simpleList)
        {
          oprot.writeI32(_iter62);
        }
      }
      {
        oprot.writeI32(struct.refList.size());
        for (SimpleStruct _iter63 : struct.refList)
        {
          _iter63.write(oprot);
        }
      }
      {
        oprot.writeI32(struct.refOtherPackageList.size());
        for (org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2 _iter64 : struct.refOtherPackageList)
        {
          _iter64.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TestListStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list65 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
        struct.simpleList = new ArrayList<Integer>(_list65.size);
        for (int _i66 = 0; _i66 < _list65.size; ++_i66)
        {
          int _elem67; // required
          _elem67 = iprot.readI32();
          struct.simpleList.add(_elem67);
        }
      }
      struct.setSimpleListIsSet(true);
      {
        org.apache.thrift.protocol.TList _list68 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.refList = new ArrayList<SimpleStruct>(_list68.size);
        for (int _i69 = 0; _i69 < _list68.size; ++_i69)
        {
          SimpleStruct _elem70; // required
          _elem70 = new SimpleStruct();
          _elem70.read(iprot);
          struct.refList.add(_elem70);
        }
      }
      struct.setRefListIsSet(true);
      {
        org.apache.thrift.protocol.TList _list71 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.refOtherPackageList = new ArrayList<org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2>(_list71.size);
        for (int _i72 = 0; _i72 < _list71.size; ++_i72)
        {
          org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2 _elem73; // required
          _elem73 = new org.disges.thrift.plugin.testdata.objects.included.package2.SimpleStructPackage2();
          _elem73.read(iprot);
          struct.refOtherPackageList.add(_elem73);
        }
      }
      struct.setRefOtherPackageListIsSet(true);
    }
  }

}

